modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="nocomplete"
version="1.0.2"
displayName="Nuovo Ordine Complete"
description='''
Server-side systems for Nuovo Ordine: strategic objectives, campaigns, contracts,
reputation, injuries, convoys, airdrops, vehicle ownership/used market and live hub.
'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.nocomplete]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.nocomplete]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="SERVER"
