modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="nopvp"
version="1.0.0"
displayName="Nuovo Ordine pvp"
description="Integrazione Nuovo Ordine: pvp."
[[dependencies.nopvp]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.nopvp]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
