modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="notownnames"
version="1.0.0"
displayName="Nuovo Ordine townnames"
description="Integrazione Nuovo Ordine: townnames."
[[dependencies.notownnames]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.notownnames]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
