modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="nocosmetics"
version="1.0.0"
displayName="Nuovo Ordine cosmetics"
description="Integrazione Nuovo Ordine: cosmetics."
[[dependencies.nocosmetics]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.nocosmetics]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
