modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="nomarket"
version="1.0.0"
displayName="Nuovo Ordine market"
description="Integrazione Nuovo Ordine: market."
[[dependencies.nomarket]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.nomarket]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
